labels: 
  Product: DevOps
  ProductComponents: monitoring
  severity: warning

image:
  repository: ghcr.io/slok/sloth
  tag: v0.11.0

# -- Container resources: requests and limits for CPU, Memory
resources:
  limits:
    cpu: 50m
    memory: 150Mi
  requests:
    cpu: 5m
    memory: 75Mi

imagePullSecrets: []
#  - name: secret1
#  - name: secret2

sloth:
  resyncInterval: ""    # The controller resync interval duration (e.g 15m).
  workers: 0            # The number of concurrent controller workers (e.g 5).
  labelSelector: slo-window=7d       # Sloth will handle only the ones that match the selector.
  namespace:          # The namespace where sloth will the CRs to process.
  extraLabels:        # Labels that will be added to all the generated SLO Rules.
    role: record-rules
  defaultSloPeriod: 7d  # The slo period used by sloth (e.g. 30d).
  optimizedRules: true  # Reduce prom load for calculating period window burnrates.
  debug:
    enabled: false
  # Could be: default or json
  logger: default

commonPlugins:
  enabled: true
  image:
    repository: k8s.gcr.io/git-sync/git-sync
    tag: v3.6.1
  gitRepo:
    url: https://github.com/slok/sloth-common-sli-plugins
    branch: main
    resources:
      limits:
        cpu: 50m
        memory: 100Mi
      requests:
        cpu: 5m
        memory: 50Mi

metrics:
  enabled: true
  #scrapeInterval: 30s
  prometheusLabels: {}

customSloConfig:
  enabled: true
  path: /windows
  data: 
    apiVersion: sloth.slok.dev/v1
    kind: AlertWindows
    spec:
      sloPeriod: 7d
      page:
        quick:
          errorBudgetPercent: 1
          shortWindow: 2m
          longWindow: 30m
        slow:
          errorBudgetPercent: 2
          shortWindow: 15m
          longWindow: 3h
      ticket:
        quick:
          errorBudgetPercent: 5
          shortWindow: 1h
          longWindow: 12h
        slow:
          errorBudgetPercent: 5
          shortWindow: 3h
          longWindow: 36h

securityContext:
  pod: null
  #   fsGroup: 100
  #   runAsGroup: 1000
  #   runAsNonRoot: true
  #   runAsUser: 100
  container: null
  #   allowPrivilegeEscalation: false
